### ISSUE TITLE
Image in Q_Learning_01.ipynb fails due to typo

### ISSUE THREAD

**Issue by danainschool** [xsankar/GTC_2019_DRL_LAB#1]
The image `QLearning_Alg.png` does not render because it is misspelled in the cell.  The "L" in Q**L**earning is capitalized in the image name, but not in the cell that calls it.

**Comment by danainschool** [comment]
Related problem:  image in `REINFORCE_01.ipynb` fails due to typo:  image named "REINFORCE_Alg_simple.png" is referenced incorrectly with a capital "S" instead of small "s" in the cell that displays it.

**Comment by xsankar** [comment]
Dana,
   Thanks a lot. I could never figure it out. Corrected and synced.
Cheers
/k
