### ISSUE TITLE
dimension error for mnist in `pytorch-example.ipynb`

### ISSUE THREAD

**Issue by danainschool** [xsankar/GTC_2019_DRL_LAB#2]
3.4 Forward pass cell #8 fails with "output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]".  This error is due to color vs grayscale on the dataset, and looks similar to this issue on another repo:  https://github.com/yunjey/pytorch-tutorial/issues/161 which was solved by changing the transform that is set up in cell #4 from 

```python
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                              ])
```

to

```python
transform = transforms.Compose([transforms.ToTensor(),
      transforms.Normalize((0.5,), (0.5,))
])
```

**Comment by xsankar** [comment]
Hi,
   Thanks. It works fine for me. I have rerun the code plus printing version numbers, just in case. Can you check that the versions are python 3.7 or something nearby and Torch 1.0 ?
Cheers
/k

**Comment by danainschool** [comment]
The code all works fine in my native 3.7 as is.  It is not an error.  

The container for the class next week (that the students will use) is running 3.5 and I cannot easily upgrade that to 3.6.  I can make these two changes locally just for the class so that it runs correctly with 3.5.

**Comment by xsankar** [comment]
Thanks for checking it out. I made the changes suggested by you and they work in 3.7. Good to make it work with as many versions as possible.
Cheers
/k
