### ISSUE TITLE
extraneous "f" in print statement causes last cell in `pytorch-example.ipynb` error

### ISSUE THREAD

**Issue by danainschool** [xsankar/GTC_2019_DRL_LAB#3]
last cell has an extra "f" in the print statement

**Comment by xsankar** [comment]
Hi, 
   It is the format-string - works fine for me. https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python. I will sync the one that works for me. See if it solves the problem.
Cheers
/k

**Comment by danainschool** [comment]
ah okay - it works in my python 3.7, but not in python 3.5 for some reason

**Comment by danainschool** [comment]
@xsankar can you  please provide a solution that works in Python 3.5?  That is what the docker container for the class provides.

**Comment by xsankar** [comment]
Hi,
  Done. Can you make sure it works ?
Cheers
/k
